TARGET_SITES = [
    {
        "name": "GitHub",
        "url_template": "https://github.com/{}",
        "category": "Development",
        "official_site": "https://github.com",
        "availability_strategy": "status_not_found",
    },
    {
        "name": "Youtube",
        "url_template": "https://youtube.com/@{}",
        "category": "Social",
        "official_site": "https://youtube.com",
        "availability_strategy": "status_not_found",
    },
    {
        "name": "DockerHub",
        "url_template": "https://hub.docker.com/u/{}",
        "category": "Development",
        "official_site": "https://hub.docker.com",
        "availability_strategy": "status_not_found",
    },
    {
        "name": "Dev.to",
        "url_template": "https://dev.to/{}",
        "category": "Development",
        "official_site": "https://dev.to",
        "availability_strategy": "status_not_found",
    },
    {
        "name": "Replit",
        "url_template": "https://replit.com/@{}",
        "category": "Development",
        "official_site": "https://replit.com",
        "availability_strategy": "status_not_found",
    },
    {
        "name": "BuyMeACoffee",
        "url_template": "https://buymeacoffee.com/{}",
        "category": "Social",
        "official_site": "https://buymeacoffee.com",
        "availability_strategy": "status_not_found",
    },
    {
        "name": "GitLab",
        "url_template": "https://gitlab.com/{}",
        "category": "Development",
        "official_site": "https://gitlab.com",
        "availability_strategy": "status_redirect",
    },
    {
        "name": "Chess.com",
        "url_template": "https://chess.com/member/{}",
        "category": "Gaming",
        "official_site": "https://chess.com",
        "availability_strategy": "status_not_found",
    },
    {
        "name": "BitBucket",
        "url_template": "https://bitbucket.org/{}/workspace/repositories",
        "category": "Development",
        "official_site": "https://bitbucket.org",
        "availability_strategy": "status_not_found",
    },
    {
        "name": "Snapchat",
        "url_template": "https://www.snapchat.com/@{}",
        "category": "Social",
        "official_site": "https://snapchat.com",
        "availability_strategy": "status_not_found",
    },
    {
        "name": "Reddit",
        "url_template": "https://www.reddit.com/user/{}",
        "category": "Social",
        "availability_strategy": "content_match",
        "not_found_phrases": [
            "Sorry, nobody on Reddit goes by that name.",
            "This account may have been banned or the username is incorrect.",
        ],
    },
    {
        "name": "Instagram",
        "url_template": "https://instagram.com/{}",
        "category": "Social",
        "availability_strategy": "status_redirect",
    },
    {
        "name": "Behance",
        "url_template": "https://www.behance.net/{}",
        "category": "Professional",
        "availability_strategy": "status_not_found",
    },
    {
        "name": "Minecraft",
        "url_template": "https://minecraftuuid.com/player/{}",
        "category": "Gaming",
        "availability_strategy": "content_match",
        "not_found_phrases": [
            "No user was found matching that username or UUID.",
            "This data may also be blocked due to a data protection request.",
        ],
    },
    {
        "name": "Xbox",
        "url_template": "https://xboxgamertag.com/search/{}",
        "category": "Gaming",
        "availability_strategy": "content_match",
        "not_found_phrases": [
            "Gamertag doesn't exist",
            "Congratulations, you've found a gamertag that is untaken. You should claim it.",
        ],
    },
    {
        "name": "Lichess",
        "url_template": "https://lichess.org/@/{}",
        "category": "Gaming",
        "availability_strategy": "status_not_found",
    },
    {
        "name": "SteamGroup",
        "url_template": "https://steamcommunity.com/groups/{}",
        "category": "Gaming",
        "availability_strategy": "content_match",
        "not_found_phrases": [
            "An error was encountered while processing your request:",
            "No group could be retrieved for the given URL.",
        ],
    },
    {
        "name": "VSCO",
        "url_template": "https://vsco.co/{}/gallery",
        "category": "Photography",
        "availability_strategy": "status_not_found",
    },
]

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:146.0) Gecko/20100101 Firefox/146.0",
    "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.7499.110 Mobile Safari/537.36",
]
